### PR TITLE
Compatibility with Semigroup/Monoid proposal

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by sjoerdvisscher** [comment]
Thanks!

**Comment by nomeata** [comment]
This has not been released yet, has it?

**Comment by sjoerdvisscher** [comment]
Working on it as we speak! Thanks to issue #2.

**Comment by sjoerdvisscher** [comment]
Done!

**Comment by sjoerdvisscher** [comment]
@bgamari This doesn't seem to work? See issue #2

**Comment by asr** [comment]
PR #3 fix the issue.

**Comment by sjoerdvisscher** [comment]
Thanks for looking into this, @asr!

**Pull request merged**
